# Generated by Django 3.1.4 on 2020-12-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название текста')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'О магазине',
            },
        ),
        migrations.CreateModel(
            name='AddCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_to_add_maps', models.CharField(max_length=64, verbose_name='Способ')),
                ('way_to_add_maps1', models.CharField(max_length=32, verbose_name='Способ1')),
            ],
            options={
                'verbose_name_plural': 'Добавить карту',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='ComplaintsAndSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Номер')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name_plural': 'Жалобы и предложение',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название одежды')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('the_size', models.PositiveIntegerField(verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежды',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Сontacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('whatsapp', models.CharField(max_length=12, unique=True, verbose_name='Whatsapp')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
                ('instagram', models.CharField(max_length=128, verbose_name='Instagram')),
                ('instagram1', models.CharField(max_length=128, verbose_name='Instagram')),
                ('instagram2', models.CharField(max_length=128, verbose_name='Instagram')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Подкатигории')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lirus.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатигории',
                'verbose_name_plural': 'Подкатигория',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='product/', verbose_name='Фотография')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='lirus.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотография',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lirus.subcategories', verbose_name='Подкатигория'),
        ),
        migrations.CreateModel(
            name='NumberCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Введите номер карты')),
                ('number_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lirus.numbercard', verbose_name='Номер карты')),
            ],
            options={
                'verbose_name_plural': 'Номер карты',
            },
        ),
    ]
