# Generated by Django 3.1.4 on 2020-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lirus', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='publish',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
    ]
