# Generated by Django 3.1.4 on 2020-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lirus', '0004_stock_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название новостей')),
                ('text', models.TextField(verbose_name='Текст')),
                ('publish', models.DateTimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name_plural': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название предложений')),
                ('text', models.TextField(verbose_name='Текст')),
                ('publish', models.DateTimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='publish',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
