# Generated by Django 3.1.4 on 2020-12-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lirus', '0005_auto_20201203_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCard',
        ),
        migrations.DeleteModel(
            name='NumberCard',
        ),
    ]
