# Generated by Django 3.1.4 on 2020-12-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lirus', '0006_auto_20201203_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.CharField(max_length=20, verbose_name='Номер карты')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Баланс')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='Скидки')),
            ],
            options={
                'verbose_name_plural': 'Карта',
            },
        ),
    ]
