# Generated by Django 3.1.4 on 2020-12-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lirus', '0007_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='the_size',
            field=models.CharField(max_length=8, verbose_name='Размер'),
        ),
    ]
