# Generated by Django 3.1.4 on 2020-12-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lirus', '0008_auto_20201203_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterModelOptions(
            name='complaintsandsuggestions',
            options={'verbose_name': 'Жалоба и предложения', 'verbose_name_plural': 'Жалобы и предложение'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи '},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акции', 'verbose_name_plural': 'Акция'},
        ),
        migrations.AlterModelOptions(
            name='сontacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
