# Generated by Django 3.1.4 on 2020-12-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lirus', '0009_auto_20201203_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='сontacts',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='сontacts',
            name='whatsapp',
            field=models.CharField(max_length=13, unique=True, verbose_name='Whatsapp'),
        ),
    ]
